name = "MRIFieldmaps"
uuid = "f8ffefc7-fd9f-4401-9d94-a27b8cc2c628"
author = ["Tobias Knopp <tobias@knoppweb.de> and contributors"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
MRIBase = "f7771a9a-6e57-4e71-863b-6e4b6a2f17df"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
julia = "1.6"
MRIBase = "0.3"
Reexport = "1"
FLoops = "0.2"
ImageUtils = "0.2.5"
FFTW = "1.0"
MRISampling = "0.1"
MRISimulation = "0.1"
MRIReco = "0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ImageUtils = "8ad4436d-4835-5a14-8bce-3ae014d2950b"
MRISimulation = "8988da37-ea20-4fa6-9af7-8a6f6f9a8970"
MRISampling = "9be66c26-f988-4649-80fc-f4721a4a33f2"
MRIReco = "bdf86e05-2d2b-5731-a332-f3fe1f9e047f"

[targets]
test = ["Test", "ImageUtils", "MRISimulation", "MRISampling", "MRIReco"]





