name = "MRIBase"
uuid = "f7771a9a-6e57-4e71-863b-6e4b6a2f17df"
author = ["Tobias Knopp <tobias@knoppweb.de>"]
version = "0.1"

[deps]
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NFFT = "efe261a4-0d2b-5849-be55-fc731d526b0d"
NFFTTools = "7424e34d-94f7-41d6-98a0-85abaf1b6c91"

[compat]
julia = "1.6"
Graphics = "1.0"
NFFT = "0.10.1"
NFFTTools = "0.2"
