name = "MRIBase"
uuid = "f7771a9a-6e57-4e71-863b-6e4b6a2f17df"
author = ["Tobias Knopp <tobias@knoppweb.de>"]
version = "0.4.6"

[deps]
AbstractNFFTs = "7f219486-4aa7-41d6-80a7-e08ef20ceed7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NFFTTools = "7424e34d-94f7-41d6-98a0-85abaf1b6c91"

[compat]
julia = "1.6"
AbstractNFFTs = "0.8, 0.9"
NFFTTools = "0.2.4, 0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]

