name = "MRISampling"
uuid = "9be66c26-f988-4649-80fc-f4721a4a33f2"
author = ["Tobias Knopp <tobias@knoppweb.de>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
MRIBase = "f7771a9a-6e57-4e71-863b-6e4b6a2f17df"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"
MRIBase = "0.2.0"
Reexport = "1"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]





